spring.application.name=shipping-service

server.port=8084

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db.zmmvlcvnncuawvyzwoyq.supabase.co:5432/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ILoveSassy@2000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

order.service.url=${ORDER_SERVICE_URL:http://localhost:8081}
order.service.integration.enabled=${ORDER_SERVICE_INTEGRATION_ENABLED:false}