spring.application.name=payment-service

server.port=${PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.apzlxjydwcxrcoiewxdt}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Payment@123Service}

spring.jpa.hibernate.ddl-auto=update

app.orderBaseUrl=${APP_ORDER_BASE_URL:http://localhost:8080}
app.internalApiKey=${APP_INTERNAL_API_KEY:sb_secret_f8ZhPKXhsVr4okTJAhuxhQ_d016z0wL}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never