spring.application.name=payment-service

server.port=8082

spring.datasource.url=jdbc:postgresql://db.apzlxjydwcxrcoiewxdt.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Payment@123Service

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.orderBaseUrl=http://localhost:8080
