server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: ${ORDER_SERVICE_URL:https://order-service.greenisland-18bb041c.southeastasia.azurecontainerapps.io}
          predicates:
            - Path=/orders/**
        - id: payments-service
          uri: ${PAYMENTS_SERVICE_URL:https://payment.gentletree-6b17349b.southeastasia.azurecontainerapps.io}
          predicates:
            - Path=/payments/**
        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:https://inventory-service.nicewave-b507020a.eastasia.azurecontainerapps.io}
          predicates:
            - Path=/inventory/**
        - id: shipping-service
          uri: ${SHIPPING_SERVICE_URL:https://shipping-service.orangeglacier-dfccfaea.southeastasia.azurecontainerapps.io}
          predicates:
            - Path=/shipping/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
